//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tennis_tournament.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tennis_tournament.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|Eufrosyne|Lisettee|Kristensen|1994-06-29|VENEZUELA, BOLIVARIAN REPUBLIC OF|VE
        ///2|Funda|Hinda|Jakobsen|1988-05-18|BOSNIA AND HERZEGOVINA|BA
        ///3|Veronika|Harda|Svensson|1984-03-22|HEARD AND MCDONALD ISLANDS|HM
        ///4|Delphine|Etty|Karlsen|1987-03-27|UNITED ARAB EMIRATES|AE
        ///5|Lela|Pim|Henriksen|1990-08-25|CYPRUS|CY
        ///6|Tinke|Toni|Holm|1990-01-08|PITCAIRN|PN
        ///7|Fatimeh|Lisser|Nielsen|1998-05-29|MACEDONIA|MK
        ///8|Arin|Neika|Vinther|1985-08-01|CHAD|TD
        ///9|Naida|Anisa|Mølgaard|1987-02-13|ZIMBABWE|ZW
        ///10|Channie|Seerah|W [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FemalePlayer {
            get {
                return ResourceManager.GetString("FemalePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|Fabiola|Micass|Bach|1969-12-17|TUVALU|TV|1995-09-23|2017-02-13
        ///2|Titt|Munder|Bjerregård|1966-04-22|GIBRALTAR|GI|1998-05-31|2017-04-09
        ///3|Maidie|Bjorgitte|Nissen|1956-05-14|QATAR|QA|2004-09-23|2016-07-11
        ///4|Joan|Sophi|Schmidt|1946-07-11|SVALBARD AND JAN MAYEN|SJ|1996-09-23|2017-05-27
        ///5|Janita|Sanny|Bjerregaard|1968-12-26|ANGOLA|AO|2008-06-14|2016-08-23
        ///6|Rosalie|Eigill|Holst|1977-01-03|BANGLADESH|BD|1999-08-29|2017-03-15
        ///7|Henni|Felan|Rasmussen|1964-01-19|BELIZE|BZ|2005-09-28|2016-10-15
        ///8|Thora|Ulrich [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FermaleRefs {
            get {
                return ResourceManager.GetString("FermaleRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|Mariuss|Luka|Thygesen|1986-07-25|NAURU|NR
        ///2|Namo|Robbert|Bruun|1985-09-13|BARBADOS|BB
        ///3|Goi|Moamel|Jakobsen|1990-03-21|BRAZIL|BR
        ///4|Shivesh|Nghia|Lind|1989-03-27|JAPAN|JP
        ///5|Cobra|Dek|Møller|1989-06-29|BANGLADESH|BD
        ///6|Micah|Connor|Lind|1986-08-14|CYPRUS|CY
        ///7|Joeri|Gehrt|Jacobsen|1994-09-22|GEORGIA|GE
        ///8|Roall|Ceejay|Lind|1987-04-03|BURKINA FASO|BF
        ///9|Raphael|Torvil|Lorenzen|1989-08-11|UKRAINE|UA
        ///10|Gerulf|Uhuru|Henriksen|1993-12-05|RWANDA|RW
        ///11|Mithuson|Okai|Lange|1995-10-21|VIRGIN ISLANDS, BRITISH| [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MalePlayer {
            get {
                return ResourceManager.GetString("MalePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|Ricco|Lesley|Jacobsen|1957-01-01|SAINT LUCIA|LC|1994-03-11|2017-10-01
        ///2|Viki|Christopher|Kjærgård|1978-05-16|SAINT PIERRE AND MIQUELON|PM|2003-11-14|2017-12-03
        ///3|Huriye|Meiner|Buch|1968-01-25|SURINAME|SR|1996-08-16|2017-05-10
        ///4|Rosalie|Eigill|Holst|1977-01-03|BANGLADESH|BD|1999-08-29|2017-03-15
        ///5|Rumeysa|Shad|Ali|1967-04-04|BHUTAN|BT|1993-10-05|2017-01-13
        ///6|Kader|Konny|Ravn|1974-10-27|AUSTRIA|AT|1999-03-18|2016-12-28
        ///7|Jamal|Freddi|Bjerregård|1960-02-15|RWANDA|RW|2001-11-02|2017-04-02
        ///8|Annee|Ruddi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MaleRefs {
            get {
                return ResourceManager.GetString("MaleRefs", resourceCulture);
            }
        }
    }
}
